# Generated by Django 4.1.2 on 2022-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_alter_tipsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsarticle',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
