# Generated by Django 4.1.2 on 2022-11-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_contactform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='user',
        ),
    ]
