# Generated by Django 4.1.2 on 2022-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='miniQuiz',
        ),
    ]
