# Generated by Django 4.1 on 2022-11-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='points',
            new_name='point',
        ),
    ]
